base_url = "https://colt45s.dev"
compile_sass = true
build_search_index = false
theme = "lightspeed"
title = "Colt45s.dev"
description = "Colt45s.dev is Colt45s' personal blog."
sort_by = "date"
date = "YYYY-mm-dd"

[markdown]
highlight_code = true

[extra]
seo = true
author = "Colt45s"
ogimage = "colt45s.jpg"
zola = false
netlify = false
maintained_with_love = false
footer_links = [
    {url = "$BASE_URL/atom.xml", name = "rss"},
    {url = "https://github.com/colt45s/colt45s.dev", name = "github"}
]